import React from "react";
import { DynamicAsset } from "@/types/course";
import { Play, Image as ImageIcon, Activity } from "lucide-react";
import { GraphCard } from "./GraphCard";

interface DynamicAssetCardProps {
  asset: DynamicAsset;
}

export const DynamicAssetCard: React.FC<DynamicAssetCardProps> = ({
  asset,
}) => {
  if (asset.type === "graph") {
    return <GraphCard equation={asset.prompt} title={asset.altText} />;
  }

  return (
    <div className="my-4 rounded-xl overflow-hidden border border-gray-200 bg-white shadow-sm">
      <div className="aspect-video bg-gray-100 flex items-center justify-center relative">
        {asset.type === "image" ? (
          <div className="text-center p-4">
            <ImageIcon className="w-12 h-12 text-gray-400 mx-auto mb-2" />
            <p className="text-sm text-gray-500 italic">{asset.altText}</p>
            <p className="text-xs text-gray-400 mt-2">
              [Nano Banana Generation Mock]
            </p>
          </div>
        ) : (
          <div className="text-center p-4">
            <Play className="w-12 h-12 text-primary-500 mx-auto mb-2" />
            <p className="text-sm text-gray-500 italic">{asset.altText}</p>
            <p className="text-xs text-gray-400 mt-2">[Veo Generation Mock]</p>
          </div>
        )}

        {/* Badge */}
        <div className="absolute top-2 right-2 bg-black/70 text-white text-[10px] px-2 py-1 rounded-full uppercase tracking-wider">
          Generated by AI
        </div>
      </div>
      <div className="p-3 bg-gray-50 border-t border-gray-100">
        <p className="text-xs font-mono text-gray-500 truncate">
          Prompt: {asset.prompt}
        </p>
      </div>
    </div>
  );
};